"""Universal Deobfuscator Core Architecture."""

from core.exceptions import (
    DeobfuscatorError,
    ParseError,
    UnsupportedLanguageError,
    SemanticPreservationError,
    AnalysisError,
)
from core.confidence import Confidence, ConfidenceEngine, ConfidenceLevel, TransformationCategory
from core.provenance import SourceLocation, ProvenanceRecord, ProvenanceTracker
from core.pipeline import Pass, Pipeline
from core.ir import (
    IRNode,
    IRExpression,
    IRStatement,
    IRConstant,
    IRString,
    IRVariable,
    IRMemberAccess,
    IRIndexAccess,
    IRBinaryOperation,
    IRUnaryOperation,
    IRCall,
    IRListLiteral,
    IRDictLiteral,
    IRAssignment,
    IRExpressionStatement,
    IRBranch,
    IRLoop,
    IRBreak,
    IRContinue,
    IRReturn,
    IRPass,
    IRTryExcept,
    IRExceptionHandler,
    IRRaise,
    IRThrow,
    IRBlock,
    IRImport,
    IRFunction,
    IRModule,
    IRVisitor,
    IRTransformer,
    IRPrinter,
    format_ir,
    IRValidator,
)
from core.ir_cfg import IRBasicBlock, IRCFG, IRCFGEdge, IREdgeType
from core.ir_pipeline import IRPipeline

__all__ = [
    "DeobfuscatorError",
    "ParseError",
    "UnsupportedLanguageError",
    "SemanticPreservationError",
    "AnalysisError",
    "Confidence",
    "ConfidenceEngine",
    "ConfidenceLevel",
    "TransformationCategory",
    "SourceLocation",
    "ProvenanceRecord",
    "ProvenanceTracker",
    "Pass",
    "Pipeline",
    "IRNode",
    "IRExpression",
    "IRStatement",
    "IRConstant",
    "IRString",
    "IRVariable",
    "IRMemberAccess",
    "IRIndexAccess",
    "IRBinaryOperation",
    "IRUnaryOperation",
    "IRCall",
    "IRListLiteral",
    "IRDictLiteral",
    "IRAssignment",
    "IRExpressionStatement",
    "IRBranch",
    "IRLoop",
    "IRBreak",
    "IRContinue",
    "IRReturn",
    "IRPass",
    "IRTryExcept",
    "IRExceptionHandler",
    "IRRaise",
    "IRThrow",
    "IRBlock",
    "IRImport",
    "IRFunction",
    "IRModule",
    "IRVisitor",
    "IRTransformer",
    "IRPrinter",
    "format_ir",
    "dump_ir",
    "IRValidator",
    "IRCFG",
    "IRBasicBlock",
    "IRCFGEdge",
    "IREdgeType",
    "IRPipeline",
]
